config/routes.rb
Rails.application.routes.draw do
  get('/', {to: 'ideas#index', as: 'root'})
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
  end
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user) 
      user ||= User.new # guest user (not logged in)
    

      can(:manage, Idea) do |idea|
        user == idea.user
      end
      can(:manage, Review) do |review|
        user == review.user 
      end   
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :idea 
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :ideas
    has_many :reviews
    
    has_secure_password()
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    helper_method :current_user
    def authenticate_user!
      unless user_signed_in?
        flash[:alert] = "You must sign in or sign up first!"
        redirect_to new_session_path
      end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :idea_find, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]
    def index
        @ideas = Idea.all.order(created_at: :desc)
    end
    def new
        @idea = Idea.new
    end
    def show
        
        @review = Review.new 
        @reviews = @idea.reviews.order(created_at: :desc)
    end
    def create 
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save
            redirect_to idea_path @idea.id
        else
            render :new 
        end

    end
    def update
        if @idea.update idea_params 
            redirect_to idea_path @idea.id
        else
            render :edit
        end
    end
    def edit
    end
    
    def destroy
       
        @idea.destroy
        redirect_to ideas_path
    end
    private
    def idea_params
        params.require(:idea).permit(:title, :description, )
    end
    def idea_find
        @idea = Idea.find(params[:id])
    end
    def authorize_user!
        unless can?(:manage, @idea)
            flash[:alert] = "Permission denied"
            redirect_to idea_path(@idea)
        end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_review, only: [:destroy]
    before_action :authorize_user!, only: [:destroy] 
    def create
        @review = Review.new review_params
        @idea = Idea.find(params[:idea_id])
        #@review = review.new(review_params)
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            redirect_to idea_path(@review.idea.id)
        else 
            @reviews = @idea.reviews.order(created_at: :desc)
            render "ideas/show"
        end
    end
    ##
    
    ##
    def destroy
        
        @review.destroy
        redirect_to idea_path(@review.idea.id)
    end

    private
    def review_params
        params.require(:review).permit(:body )
    end
    def find_review
        @review = Review.find params[:id]
    end
    def authorize_user!
        unless can?(:manage, @review)
            flash[:alert] = "Permission denied"
            redirect_to idea_path(@review.idea)
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
      user = User.find_by(email: params[:session][:email])
  
      if user&.authenticate(params[:session][:password])
        session[:user_id] = user.id
  
        flash[:notice] = "Thanks for signing in, #{user.name}!"
        redirect_to root_path
      else
        flash[:alert] = "Invalid email or password!"
        redirect_to new_session_path
      end
    end
    def destroy
      session[:user_id] = nil 
      flash[:notice] = "Successfully signed out!"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def new
        @user = User.new
    end
    def edit 
    end
    def update
    end
    def create
        @user = User.new user_params  
        if @user.save
          session[:user_id] = @user.id
    
          flash[:notice] = "Thank you, #{@user.name}, for signing up!"
          redirect_to root_path
        else
          render :new
        end
    end
    
      private
      def user_params
        params.require(:user).permit(
          :name, :email, :password, :password_confirmation
        )
      end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= form_for(@idea) do |f| %>
  <% if @idea.errors.present? %>
    <p>
      <%= @idea.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <%= f.submit 'Update Idea' , class: "btn btn-outline-primary" %>
<% end %>

app/views/ideas/index.html.erb
<div class = "col">
<% @ideas.each do |idea| %>
          <div class="container">
          <div class="idea-container"> 
         
              <h4><%= idea.title %></h4>
                
              </h3>
              <div class = "plus-sign">
                <%= image_tag("30px-list-add.png", :alt => "plus") %>
              </div>
              <div class="idea-description">
              
              <p >
              <div class = "toggler">
              <%= image_tag("30px-list-remove.png", :alt => "minus") %>
                <%= idea.description %>
              </div>
              <p>
              
              </div>
              <div class="d-flex justify-content-between">
              <div class="d-flex justify-content-start">
              
                <h5><%= link_to "By #{idea.user.name}", idea_path(idea) %></h5> 
              <button type="button" class="btn btn-light">Joined</button>
              <button type="button" class="btn btn-light">Like</button>
              
                </div>
              
                <h5>Members: 5 | Likes: 5</h5>
              
              </div>
          </div>    
          </div>
         
        
  <% end %>

  </div>

app/views/ideas/new.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.present? %>
    <p>
      <%= @idea.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <%= f.submit 'Create Idea' , class: "btn btn-outline-primary" %>
<% end %>

app/views/ideas/show.html.erb
<div>
<h1><%= @idea.title %></h1>
<p><%= @idea.description %></p>
</div>
<div>
<small>
    Posted <%= time_ago_in_words(@idea.created_at) %> ago by  <%= @idea.user&.name || "[DELETED]" %>
  </small>
  •
  <small>
    Last edited <%= time_ago_in_words(@idea.updated_at) %> ago
  </small>
</div>
  <div>
    <small><%= link_to "Edit", edit_idea_path(@idea) %></small>

    <small>
      <%= link_to(
        "Delete",
        idea_path(@idea),
        method: :delete,
        data: {
          confirm: "Are you sure?"
        }
      ) %>
    </small>
</div>

<h2>Reviews for this idea</h2>



<%= form_for [@idea, @review] do |f| %>
  <% if @review.errors.present? %>
    <p>
      <%= @review.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div>
    <%= f.text_area(
      :body,
      cols: 60,
      rows: 6,
      placeholder: "Give your feedback for this idea"
    ) %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

<div class="review-list">
  <% @reviews.each do |review| %>
    <div>
      
      
      <p>
        <%= review.body %> <br />
       
          <small>
            <%= link_to(
              "Delete",
              idea_review_path(@idea.id, review.id),
              method: :delete,
              data: {
                confirm: "Are you sure?"
              }
            ) %>
          </small>
          •
        
        <small>
          Posted <%= time_ago_in_words(review.created_at) %> ago by <%= review.user&.name || "[DELETED]" %>
        </small>
        
        
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'custom.js' %>
  </head>

  <body>
<nav class="navbar ">
    <a class="navbar-brand text-primary" style="font-size: 2rem" href="/">I D E A   M A T R I X</a>
    <span>
    
    <% if user_signed_in? %>
      <span style="font-size: 1.5rem">Hello, <%= current_user.name %>!</span>
      
      <%= link_to( 
        'Sign Out',
        session_path, 
        method: :delete,
        :style=>"font-size: 1.5rem")
       %>
    <% else %>
      <%= link_to 'Sign In', new_session_path, {:style=>"font-size: 1.5rem"} %>
     
      <%= link_to 'Sign Up', new_user_path, {:style=>"font-size: 1.5rem"} %>
    <% end %>
    <div class="d-flex justify-content-end">
    <div class="custom-button">
    <%= link_to " New Idea", new_idea_path, {:style=>"font-size: 1.5rem"}  %>
    </div>
    </div>




    </span>
    </nav>
    
    

    <hr>


    <div class = "container-fluid">
    <% flash.each do |type, msg| %>
     <div
          class="alert alert-<%= type == "alert" ? "danger" : "success" %> alert-dismissible fade show"
          role="alert"
        >
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      
    <% end %>

    </div>


    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <p>
      <%= @user.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Sign Up"%>
<% end %>